name = "Diddlers"
author = "Aaron"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "509375b8b64d97c6a658cf66941fdb918ad430b534bf23d5cf692a310bd54055"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
